### ISSUE TITLE
tempo2 on conda-forge?

### ISSUE THREAD

**Issue by mattpitkin** [demorest/tempo2-conda#1]
Hi @demorest, I was just thinking of packaging tempo2 for conda myself, but it looks like you've already done it! Does this packaging work and are you planning to put it on conda-forge?

**Comment by demorest** [comment]
Hi @mattpitkin yes, it works.  The results for now are available in my conda channel (anaconda.org/demorest) if you want to try it out.  I've thought about putting this (and other pulsar stuff) on conda-forge.  Would you be interested in seeing this happen?

**Comment by mattpitkin** [comment]
Excellent. I'll give it a go installing it from your channel, but I think it (and your packaging of tempo and the associated clock files) would be great to have the additional visibility and findability of being on the main conda-forge channel. I actually found your packaging through the fact that you'd had to do the packaging for pgplot (I assume because you were trying to package tempo2?). If you go down the route or putting it on conda-forge I'd be happy to help of necessary.

My reason for thinking about packaging it myself was to make it easier for my new PhD student to install, so I'll also point them to it.

**Comment by demorest** [comment]
Yeah, there are several pulsar packages that need pgplot.  There was actually a conda-forge version of pgplot already but it needed a couple tweaks to work correctly with these codes.  OK, I'll take a look at this sometime this week.  Have you packaged things for conda-forge before?

**Comment by demorest** [comment]
PS I just updated this to use the latest named version of tempo2 (2020.07.1), will be available soon when the build finishes.

**Comment by mattpitkin** [comment]
> Have you packaged things for conda-forge before?

Yep, I've added a few things to conda-forge. As you've already got the recipe and build scripts it should be fairly straightforward to do.

**Comment by mattpitkin** [comment]
I'll just add @sixbynine in here to see if he's happy about getting tempo2 in conda-forge.

**Comment by mattpitkin** [comment]
I can close this now!
